[window]
padding = {x = 7, y = 7}
title = "cocotreb@tpt14g5:~"
dynamic_title = true
opacity = 1

[font]
normal = {family = "JetBrainsMonoNerdFont"}
size = 13

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#333333'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
